#!/usr/bin/env python3
"""make_report.py - merge perf.csv + synth.csv into the stock-vs-MXINT8 comparison report.

Reads DOCS_MX/scripts/results/{perf,synth}.csv (produced by run_perf.sh / run_synth.sh)
and writes results/comparison_report.md with, per DIM:
  - cycles / MACs-per-cycle / utilization / latency / throughput per shape and impl,
    with the MX-vs-stock cycle overhead;
  - the synthesis resource and Fmax_est deltas.

Latency and ops/s use each config's own OOC Fmax estimate (synthesis-only, no P&R - the
caveat is printed in the report). Stdlib only.
"""

import csv
import os
import sys
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(SCRIPT_DIR, "results")
PERF_CSV = os.path.join(RESULTS, "perf.csv")
SYNTH_CSV = os.path.join(RESULTS, "synth.csv")
OUT_MD = os.path.join(RESULTS, "comparison_report.md")


def read_csv(path):
    if not os.path.exists(path):
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def fmt(x, nd=2):
    try:
        return f"{float(x):,.{nd}f}"
    except (TypeError, ValueError):
        return "-"


def main():
    perf = read_csv(PERF_CSV)
    synth = read_csv(SYNTH_CSV)
    if not perf and not synth:
        sys.exit(f"no input data: {PERF_CSV} / {SYNTH_CSV}")

    synth_by_cfg = {r["config"]: r for r in synth}

    # perf rows keyed by (dim, shape) -> {impl: row}
    by_dim = defaultdict(lambda: defaultdict(dict))
    for r in perf:
        shape = (int(r["M"]), int(r["N"]), int(r["K"]))
        by_dim[int(r["dim"])][shape][r["impl"]] = r

    lines = []
    w = lines.append
    w("# Stock vs MXINT8 comparison report")
    w("")
    w("Generated by `make_report.py` from `perf.csv` (Verilator cycle counts; timed")
    w("region = payload/scale mvins + compute + mvout, quantization excluded on both")
    w("sides, full_C output) and `synth.csv` (Vivado out-of-context synthesis of the")
    w("`Gemmini` tile, identical part/constraints per run; **synthesis-only Fmax")
    w("estimate, no place-and-route**). Latency/throughput columns use each config's")
    w("own Fmax_est.")
    w("")

    for dim in sorted(by_dim.keys(), reverse=True):
        w(f"## DIM = {dim}")
        w("")
        stock_cfg = f"GemminiStockDIM{dim}RocketConfig"
        mx_cfg = f"GemminiMXINT8DIM{dim}RocketConfig"
        fmax = {}
        for impl, cfg in (("stock", stock_cfg), ("mx", mx_cfg)):
            srow = synth_by_cfg.get(cfg)
            fmax[impl] = float(srow["fmax_mhz"]) if srow and srow.get("fmax_mhz") else None

        # --- performance table ---
        w("### Performance (Verilator cycles)")
        w("")
        w("| shape (MxNxK) | impl | result | cycles | MACs/cycle | util % | latency @Fmax_est | GOPS @Fmax_est | MX overhead % |")
        w("|---|---|---|---:|---:|---:|---:|---:|---:|")
        for shape in sorted(by_dim[dim].keys()):
            m, n, k = shape
            rows = by_dim[dim][shape]
            stock_cycles = float(rows["stock"]["cycles"]) if "stock" in rows else None
            for impl in ("stock", "mx"):
                if impl not in rows:
                    continue
                r = rows[impl]
                cycles = float(r["cycles"])
                macs = float(r["macs"])
                mpc = macs / cycles if cycles else 0.0
                lat = gops = "-"
                if fmax[impl]:
                    lat = f"{cycles / (fmax[impl] * 1e6) * 1e3:,.3f} ms"
                    gops = fmt(2 * mpc * fmax[impl] / 1e3, 2)  # 2 ops/MAC, GHz*ops
                ovh = "-"
                if impl == "mx" and stock_cycles:
                    ovh = fmt((cycles - stock_cycles) / stock_cycles * 100.0, 2)
                w(f"| {m}x{n}x{k} | {impl} | {r['result']} | {int(cycles):,} | "
                  f"{fmt(mpc)} | {r['util_pct']} | {lat} | {gops} | {ovh} |")
        w("")

        # --- synthesis table ---
        srows = [(impl, synth_by_cfg.get(cfg))
                 for impl, cfg in (("stock", stock_cfg), ("mx", mx_cfg))]
        if any(s for _, s in srows):
            w("### Synthesis (Vivado OOC, Nexys Video XC7A200T)")
            w("")
            w("| impl | LUT | FF | BRAM36 | DSP | WNS (ns) | Fmax_est (MHz) |")
            w("|---|---:|---:|---:|---:|---:|---:|")
            for impl, s in srows:
                if not s:
                    continue
                w(f"| {impl} | {int(float(s['lut'])):,} | {int(float(s['ff'])):,} | "
                  f"{s['bram36']} | {s['dsp']} | {s['wns_ns']} | {fmt(s['fmax_mhz'])} |")
            st, mx = srows[0][1], srows[1][1]
            if st and mx:
                dl = float(mx["lut"]) - float(st["lut"])
                df = float(mx["ff"]) - float(st["ff"])
                w(f"| **MX delta** | {dl:+,.0f} ({dl / float(st['lut']) * 100:+.1f}%) | "
                  f"{df:+,.0f} ({df / float(st['ff']) * 100:+.1f}%) | "
                  f"{float(mx['bram36']) - float(st['bram36']):+.1f} | "
                  f"{float(mx['dsp']) - float(st['dsp']):+.0f} | - | "
                  f"{float(mx['fmax_mhz']) - float(st['fmax_mhz']):+.1f} |")
            w("")

    with open(OUT_MD, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
